### ISSUE TITLE
Data files are missing 

### ISSUE THREAD

**Issue by alitinsky** [fabriziobasso/Forecasting_a_Recession_in_the_USA_Chapter_I#1]
Fabrizio,
This is a great submission. 
Can you please upload data files or   comment  on data sources.
Thanks
Alex

**Comment by fabriziobasso** [comment]
Hi Alex,

Fair point! I added the files which were used in the first article of the series.  In the second article, I added a brief description of the time series used in the analysis. However, since I publish it, I realized that all those series are available from the Pandas_datareader library and the data providers it relies on.  If you are interested in the topic and would like to discuss ideas, improvements, application, etc, just let me know! Kind regards, Fabrizio

**Comment by alitinsky** [comment]
Hi Fabrizio,
Thanks a  lot for your update. I am reading your blog and Python code and enjoy it 
Best  wishes and will be in touch.
Sincerely.
Alex
